"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000

format = '$all'

[character]
success_symbol = "[|](bold #e46876)"
error_symbol = "[|](bold #e46876)"

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = 'ó° … '
style = 'blue bold'

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '


[time]
disabled = false
format = '[\[$time\]]($style)'
style = "fg:#585858"
time_format = "%H:%M"


[git_branch]
symbol = "ï˜ "
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "purple"

[git_status]
format = '([\($all_status$ahead_behind\)]($style))'
diverged = "<>â‡¡${ahead_count} â‡£${behind_count} "
conflicted = "=${count} "
behind = "â‡£${count}"
ahead = "â‡¡${count}"
modified = "~${count}"
untracked = "?${count}"
stashed = "^${count}"
staged = "+${count}"
deleted = "x${count}"
renamed = "Â»${count}"
style = "red"

[status]
disabled = false
format = "[$symbol $status]($style)"
symbol = "î€"
signal_symbol = "ïƒ§"
sigint_symbol = "ğ¥‰‰"
not_found_symbol = "ï™™"
not_executable_symbol = "ï¡¶"

[cmd_duration]
disabled = false
min_time = 2_000
show_milliseconds = false
format = " [ï‰’ $duration](grey) "

[directory]
truncate_to_repo = false
truncation_length = 1
style = "green"
read_only = " ï ½"
format = '[$path]($style)[$read_only]($read_only_style) '

[c]
format = "[$symbol($version(-$name) )]($style)"
symbol = "î˜ "

[docker_context]
format = "[$symbol$context ]($style)"
symbol = "ïŒˆ "

[elixir]
format = '[$symbol($version \(OTP $otp_version\) )]($style)'
symbol = "î‰µ "

[golang]
format = "[$symbol($version )]($style)"
symbol = "î˜§ "

[nodejs]
format = "[$symbol($version )]($style)"
symbol = "îœ˜ "

[package]
symbol = "ğŸ“¦"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "îˆµ "

[rust]
format = "[$symbol($version)]($style)"

[lua]
format = "[$symbol($version )]($style)"
symbol = "î˜  "

[jobs]
symbol = "ï‚… "

[terraform]
format = '[$symbol$version]($style) '
